# Generated by Django 2.0.2 on 2018-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_language', models.CharField(choices=[('EN', 'English'), ('TH', 'Thai')], default='TH', max_length=2)),
                ('address_reference_number', models.CharField(blank=True, max_length=10, null=True)),
                ('plot_house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building_mu', models.CharField(blank=True, max_length=50, null=True)),
                ('street_road', models.CharField(blank=True, max_length=50, null=True)),
                ('khet_tambon', models.CharField(blank=True, max_length=50, null=True)),
                ('kwaeng_amphoe', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('national_id_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_language', models.CharField(choices=[('EN', 'English'), ('TH', 'Thai')], default='TH', max_length=2)),
                ('name_reference_number', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_language', models.CharField(choices=[('EN', 'English'), ('TH', 'Thai')], default='TH', max_length=2)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('address_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_en', to='student.AddressInfo')),
                ('address_th', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_th', to='student.AddressInfo')),
                ('extra_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.AddressInfo')),
                ('name_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name_en', to='student.NameInfo')),
                ('name_th', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name_th', to='student.NameInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('other', 'Other')], default='mother', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Parent')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='student.NationalityInfo'),
        ),
    ]
